x-airflow-common: &airflow-common
  build:
    context: ./docker_image/airflow
    dockerfile: Dockerfile
  env_file:
    - ./docker_image/airflow/airflow.env
  volumes:
    - ./dags_or_jobs:/opt/airflow/dags              # DAGs theo format mới
    - ./src:/opt/airflow/jobs                       # các script Python
    - ./logs:/opt/airflow/logs                      # log output
    - ./data:/opt/airflow/data                      # CSV đầu vào nếu có
    - /var/run/docker.sock:/var/run/docker.sock
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  superset:
    build:
      context: ./docker_image/superset
      dockerfile: Dockerfile
    container_name: superset-app
    env_file:
      - .env
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8085:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
               airflow scheduler"

volumes:
  postgres-db-volume:
  superset_home:

networks:
  default:
    driver: bridge
